apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-webapp
  template:
    metadata:
      labels:
        app: sample-webapp
    spec:
      containers:
        - name: sample-webapp
          image: aman65f/sample-webapp:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: sample-webapp-service
spec:
  type: LoadBalancer
  selector:
    app: sample-webapp
  ports:
    - port: 80
      targetPort: 3000

